#!/usr/bin/env python

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(start=-50, stop=50, num=5000)

fig, ax = plt.subplots()
ax.plot(x, x**2 + 10)
ax.plot(x, (x - 30) ** 2 + 10)
ax.plot(x, (x + 30) ** 2 + 10)
ax.set_xlim(-50, 50)
ax.set_ylim(0, 100)
plt.axvline(x=15, color="DarkRed", linewidth=0.8, linestyle=":")
plt.axvline(x=0, color="gray", linewidth=1, linestyle="-")
plt.axhline(y=0, color="gray", linewidth=1, linestyle="-")
ax.text(x=16, y=1, s=r"$\frac{1}{q}$", fontdict=dict(size=12))
ax.set_title(r"$\Delta<0$")
ax.grid()
# ax.set_aspect(aspect="equal")
plt.savefig("Deltanegative.pdf")

fig, ax = plt.subplots()
ax.plot(x, x**2)
ax.plot(x, (x - 30) ** 2)
ax.plot(x, (x + 30) ** 2)
ax.set_xlim(-50, 50)
ax.set_ylim(0, 100)
plt.axvline(x=15, color="DarkRed", linewidth=0.8, linestyle=":")
plt.axvline(x=0, color="gray", linewidth=1, linestyle="-")
plt.axhline(y=0, color="gray", linewidth=1, linestyle="-")
ax.text(x=16, y=1, s=r"$\frac{1}{q}$", fontdict=dict(size=12))
ax.set_title(r"$\Delta=0$")
ax.grid()
# ax.set_aspect(aspect="equal")
plt.savefig("Deltazero.pdf")

fig, ax = plt.subplots()
ax.plot(x, x**2 - 10)
ax.plot(x, (x - 30) ** 2 - 10)
ax.plot(x, (x + 30) ** 2 - 10)
ax.set_xlim(-50, 50)
ax.set_ylim(-10, 90)
plt.axvline(x=15, color="DarkRed", linewidth=0.8, linestyle=":")
plt.axvline(x=0, color="gray", linewidth=1, linestyle="-")
plt.axhline(y=0, color="gray", linewidth=1, linestyle="-")
ax.text(x=16, y=-10, s=r"$\frac{1}{q}$", fontdict=dict(size=12))
ax.set_title(r"$\Delta>0$")
ax.grid()
# ax.set_aspect(aspect="equal")
plt.savefig("Deltapositive.pdf")
