[parameters]
α = 1.0
tast = "1/kp" # Calculated later
β = "(α * tast) / Cm" # Calculated later
a1 = 0.00189
b3 = 1.0
b1 = 1.1
c = 1.0
a3 = 0.00252
Tast = 300.0
b2 = 30.4
a2 = 27.6
SoR = 1.0
SyL = "-(b2 * (c - a3) * SoR) / (b3 * (c - a2))" # Calculated later
θ0 = 1.0
q = "(a1 * b3) / (b1 * (c - a3))" # Calculated later
m = "(β * SoR) / (b1 * SyL * tast * kp)" # Calculated later
ε = "Er / (R * Tast)" # Calculated later


# Parameters for Case II
[case_ii]
α = 1.0
kp = 24556.0
Cm = 2000000.0
tast = "1/kp" # Calculated later
β = "(α * tast) / Cm" # Calculated later
a1 = 0.00189
b3 = 1.0
b1 = 1.1
SyL = 1.0
a3 = 0.00252
Er = 51247.0
R = 8.314
Tast = 300.0
b2 = 30.4
a2 = 27.6
SoR = 1.0
c = "(a2 * b3 * SyL + a3 * b2 * SoR) / (b2 * SoR + b3 * SyL)" # Calculated later
θ0 = 1.0
q = "(a1 * b3) / (b1 * (c - a3))" # Calculated later
m = "(β * SoR) / (b1 * SyL * tast * kp)" # Calculated later
ε = "Er / (R * Tast)" # Calculated later

[case_angelbeta]
w = 1.0
α = 1.0
khat = 1e10
kp = 24556.0
Cm = 2e6
Qr = 4.4e5
tast = "1/kp" # Calculated later
β = "(α * tast) / Cm" # Calculated later
a1 = 0.00189
b3 = 1.0
b1 = 1.1
SyL = 1.0
a3 = 0.00252
Er = 51247.0
R = 8.314
Tast = 300.0
b2 = 30.4
a2 = 27.6
SoR = 1.0
c = "(a2 * b3 * SyL + a3 * b2 * SoR) / (b2 * SoR + b3 * SyL)" # Calculated later
θ0 = 1.0
q = "(a1 * b3) / (b1 * (c - a3))" # Calculated later
m = "(β * SoR) / (b1 * SyL * tast * kp)" # Calculated later
ε = "Er / (R * Tast)" # Calculated later
