name: LaTeX

on:
  push:
    branches: [main]
    paths:
      - exercises/**
      - quizes/**
      - report/**
      - slides/**
      - syllabus/**
      - template/**
      - monograph/**

jobs:
  build_latex:
    runs-on: ubuntu-24.04

    steps:
      - name: Partial Clone
        shell: bash
        run: |
          REPO="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          # git config --global init.defaultBranch main
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git clone -q --filter=blob:none --no-checkout --depth=1  --sparse $REPO .
          git sparse-checkout init --cone
          git sparse-checkout set exercises quizes report slides snapshots syllabus template
          git checkout

      - uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
          image: ghcr.io/cpp-review-dune/introductory-review/texlive:latest
          options: |
            -v ${{github.workspace}}:/work
          shell: bash
          run: |
            sudo chown -R gitpod:gitpod /work
            sudo pacman -Syu --needed --noconfirm python-matplotlib python-qrcode
            pushd /work/exercises
            arara exercises
            popd
            pushd /work/quizes
            arara entrance entrancebeamer #week1
            popd
            pushd /work/report
            ./figure1.py
            ./figure2.py
            ./figure3.py
            arara main
            popd
            pushd /work/slides
            ./figure1.py
            ./figure3.py
            arara presentation
            popd
            pushd /work/syllabus
            ./qr.py
            arara syllabus
            popd
            pushd /work/template
            arara amsart-template
            popd
            pushd /work/monograph
            arara book
            popd
            mkdir -p /work/public
            mv /work/exercises/exercises.pdf /work/public
            mv /work/quizes/entrance*.pdf /work/public
            mv /work/report/main.pdf /work/public
            mv /work/slides/presentation.pdf /work/public
            mv /work/syllabus/syllabus.pdf /work/public
            mv /work/template/amsart-template.pdf /work/public
            mv /work/monograph/book.pdf /work/public

      - name: "Tar files"
        run: |
          sudo chown runner:docker -R .
          tar --zstd -cf PDF.tar.zst public/*.pdf
  
      - uses: actions/upload-artifact@v4
        with:
          name: PDF-artifact
          path: PDF.tar.zst
          if-no-files-found: error
          retention-days: 90